---
- name: Intall repositories packaged as RPMs
  yum:
    name:
      - centos-release
      - epel-release
    state: 'present'

- name: Configure known repo files
  copy:
    src: '{{ item }}'
    dest: /etc/yum.repos.d
    owner: root
    group: root
    mode: 0644
  loop:
    - nodesource-el7.repo
