---
- import_tasks: install_repo.yml
  loop: '{{ repos_releases }}'

- name: Install required GPG keys
  copy:
    src: '{{ item }}'
    dest: /etc/pki/rpm-gpg
    owner: root
    group: root
    mode: 0644
  loop:
    - NODESOURCE-GPG-SIGNING-KEY-EL
    
- name: Configure known repo files
  copy:
    src: '{{ item }}'
    dest: /etc/yum.repos.d
    owner: root
    group: root
    mode: 0644
  loop:
    - nodesource-el7.repo
