---
- name: Install HAProxy
  yum:
    name: haproxy
    state: latest

- name: Configure firewalld for haproxy
  firewalld: 
    service: https
    permanent: yes
    state: enabled
    immediate: yes

- name: Configure haproxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: 0644
  notify: Reload haproxy

- name: Start and enable HAProxy
  service:
    name: haproxy
    state: started
    enabled: yes
