---
- name: Install prereq packages
  yum:
    name:
      - java-1.8.0-openjdk
    state: present

- name: Create the nexus user
  user:
    state: present
    name: nexus
    shell: /bin/bash

- name: Download the Nexus3 software
  get_url:
    url: '{{ nexus3_downloadUrl }}'
    dest: '{{ nexus3_downloadDir }}'
    checksum: '{{ nexus3_downloadChecksum }}'
  register: nexusDownload

- name: Create the Nexus3 installation directory
  file:
    state: directory
    path: '{{ nexus3_installDir }}'
    owner: root
    group: nexus
    mode: 0770

- name: Unarchive Nexus3
  unarchive:
    remote_src: yes
    src: '{{ nexusDownload.dest }}'
    dest: '{{ nexus3_installDir }}'
    owner: root
    group: nexus

- name: Find the nexus binary
  command: find {{ nexus3_installDir }} -path '*bin/nexus'
  changed_when: false
  register: nexusBinary

- name: Render the systemd file
  template:
    src: nexus.service.j2
    dest: /etc/systemd/system/nexus.service
    owner: root
    group: root
    mode: 0644
  notify:
    - Reload systemd

- name: Set proper permissions on Nexus directory
  file:
    path: '{{ nexus3_installDir }}'
    owner: root
    group: nexus
    mode: u=rwX,g=rwX,o=rX
    recurse: yes

- name: Enable firewall
  firewalld:
    port: '{{ nexus3_port }}/tcp'
    immediate: true
    permanent: true
    state: enabled

- name: Configure nexus
  template:
    src: nexus.properties.j2
    dest: '{{ nexus3_installDir }}/sonatype-work/nexus3/etc/nexus.properties'
    owner: root
    group: nexus
    mode: 0664
  notify: Restart nexus

- name: Start and enable Nexus
  service:
    name: nexus
    state: started
    enabled: yes
