---
- name: Configure Rsyslog
  template: 
    src: rsyslog.conf.j2
    dest: /etc/rsyslog.conf
    owner: root
    group: root
    mode: 0644
  notify: Restart rsyslog

- name: Configure Selinux to handle remote syslog ports
  seport:
    ports: '{{ syslog_port_t }}'
    proto: tcp
    setype: syslogd_port_t
    state: present
