---
- name: Install required packages
  yum:
    name:
      - vim
      - git
      - ansible
      - nodejs
      - policycoreutils-python
      - psmisc
      - lsof
      - htop
    state: present

- name: Install required NPM packages
  npm:
    name: '{{ item }}'
    global: yes
  loop:
    - axios
    - htmlparser2
