---
- name: Create the anaconda app webhook
  import_role:
    name: anaconda_app
  vars:
    anaconda_app_user: '{{ custom_webhooks_user }}'
    anaconda_app_installDir: '{{ custom_webhooks_installDir }}'
    anaconda_app_condaEnvironment: '{{ custom_webhooks_condaEnvironment }}'
    anaconda_app_dependencies: '{{ custom_webhooks_dependencies }}'
    anaconda_app_condaHome: '{{ custom_webhooks_condaHome }}'
    anaconda_app_pipDependencies: '{{ custom_webhooks_pipDependencies }}'

- name: Create the secrets file
  copy:
    content: '{{ custom_webhooks_secret }}'
    dest: '{{ custom_webhooks_installDir }}/secret'
    owner: '{{ custom_webhooks_user }}'
    group: '{{ custom_webhooks_user }}'
    mode: 0600

- name: Install the webhook service
  template:
    src: webhook.service
    dest: /etc/systemd/system
    owner: root
    group: root
    mode: 0644
  notify: Reload systemd

- name: Install the webhook app
  template: 
    src: webhook.py
    dest: '{{ custom_webhooks_installDir }}'
    owner: '{{ custom_webhooks_user }}'
    group: '{{ custom_webhooks_user }}'
    mode: 0640
  notify: Restart webhook

- name: Configure the firewall
  firewalld:
    port: '{{ custom_webhooks_port }}/tcp'
    permanent: yes
    state: enabled
    immediate: yes

- name: Start and enable the webhook service
  service:
    name: webhook
    state: started
    enabled: yes
