---
- name: Remove old versions of docker
  yum:
    name:
      - docker
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      - docker-engine
    state: absent

- name: Configure the docker community enterprise repository
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
    checksum: 'sha256:6650718e0fe5202ae7618521f695d43a8bc051c539d7570f0edbfa5b4916f218'

- name: Install Docker and pre-req packages
  yum:
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
      - docker-ce
    state: present

- name: Start and enable the docker service
  service:
    name: docker
    state: started
    enabled: yes
