---
- import_tasks: db_provision.yml
  become_user: postgres
  become: true
  delegate_to: '{{ flask_app_dbServer }}'

- name: Install sudoers for app user
  template:
    src: 'app_service'
    dest: /etc/sudoers.d
    owner: root
    group: root
    mode: 0600
    enabled: yes
