---
- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Remove the virtual machine
      ovirt_host:
        auth:
          insecure: true
        state: absent
        name: '{{ delete_host }}'
