---
- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Remove the virtual machine
      ovirt_host:
        auth:
          hostname: '{{ lookup("env", "OVIRT_HOSTNAME") }}'
          username: '{{ lookup("env", "OVIRT_USERNAME") }}'
          password: '{{ lookup("env", "OVIRT_PASSWORD") }}'
          insecure: true
        state: absent
        force: True
        name: '{{ delete_host }}'
