---
- hosts: linux
  become: True
  environment:
    NODE_PATH: '/usr/lib/node_modules'
  roles:
    - sudoers
    - known_hosts
    - repos
    - software
    - static-hosts
    - domain
    - anaconda
    - fips
