---
- name: Create the {{ anaconda_app_user }} user
  user:
    name: '{{ anaconda_app_user }}'

- name: Create the {{ anaconda_app_installDir }} directory
  file:
    path: '{{ anaconda_app_installDir }}'
    state: directory
    owner: '{{ anaconda_app_user }}'
    group: '{{ anaconda_app_user }}'
    mode: 0750

- name: Create the anaconda environment {{ anaconda_app_condaEnvironment }}
  anaconda:
    name: '{{ anaconda_app_condaEnvironment }}'
    packages: '{{ anaconda_app_dependencies }}'
    channels:
      - conda-forge
    state: present
    executable: '{{ anaconda_app_condaHome }}/bin/conda'

- name: Install packages only available through pip
  pip:
    name: '{{ anaconda_app_pipDependencies }}'
    executable: '{{ anaconda_app_condaHome }}/envs/{{ anaconda_app_condaEnvironment }}/bin/pip'
