---
- name: Restart icinga2
  service:
    name: icinga2
    state: restarted

- name: Restart httpd
  service:
    name: httpd
    state: restarted

- name: Restart php-fpm
  service:
    name: rh-php71-php-fpm
    state: restarted
