---
- name: Install Jenkins public key
  rpm_key:
    state: present
    key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key

- name: Configure Jenkins repo
  get_url:
    url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo
    owner: root
    group: root
    mode: 0644

- name: Configure Jenkins startup options
  copy:
    src: jenkins
    dest: /etc/sysconfig
    owner: root
    group: root
    mode: 0600
  notify: Restart jenkins

- name: Ensure certain Jenkins directories exist due to bug in Jenkins RPM
  file:
    state: directory
    path: '{{ item }}'
  loop:
    - /var/cache/jenkins
    - /var/log/jenkins
    - /var/lib/jenkins

- name: Install Jenkins
  yum:
    name: 
      - java-1.8.0-openjdk
      - jenkins
    state: present

- name: Configure firewalld for Jenkins
  firewalld:
    port: 8080/tcp
    permanent: yes
    state: enabled
    immediate: yes

- name: Start and enable Jenkins
  service:
    name: jenkins
    state: started
    enabled: yes
