---
- name: Restart haproxy
  service:
    name: haproxy
    state: restarted

- name: Restart rsyslog
  service:
    name: rsyslog
    state: restarted

- name: Generate new bundle
  shell: cat fullchain.pem privkey.pem > fullCert.pem
  args:
    chdir: /etc/pki/tls/certs

- name: Set bundle permissions
  file:
    path: /etc/pki/tls/certs/fullCert.pem
    state: file
    mode: 0640
    owner: root
    group: haproxy
