---
- name: Install Elasticsearch
  yum:
    state: present
    name: elasticsearch

- name: Configure Elasticsearch
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: elasticsearch
    mode: 0660
  notify: Restart elasticsearch
    
- name: Configure firewall for Elasticsearch
  firewalld:
    port: '{{ item }}'
    permanent: yes
    immediate: yes
    state: enabled
  loop:
    - 9200/tcp
    - 9300/tcp

- name: Start and enable Elasticsearch
  service:
    name: elasticsearch
    state: started
    enabled: yes
