---
- hosts: localhost
  connection: local
  vars:
    ks_host: https://192.168.1.20/ks
  tasks:
    - name: Create the vm disk
      ovirt_disk:
        activate: true
        bootable: true
        interface: virtio_virtio
        storage_domain: Data
        name: '{{ create_host }}_disk'
        size: 50GiB
        state: present
        wait: true


    - name: Create the vm
      ovirt_vm:
        cluster: Default
        name: '{{ create_host }}'
        state: present
        memory: 2GiB
        cpu_cores: 2
        type: server
        operating_system: rhel_8x64
        boot_devices:
          - hd
          - network
        disks:
          - name: '{{ create_host }}_disk'
            bootable: True
        nics:
          - name: nic1


    - name: Update the vm nic
      ovirt_nic:
        vm: '{{ create_host }}'
        name: nic1
        state: plugged
        interface: virtio
        profile: ovirtmgmt
        network: ovirtmgmt
        wait: yes


    - name: Get the vm nic info
      ovirt_nic_info:
        vm: '{{ create_host }}'
      register: ovirt_nics


    - name: Start the vm
      ovirt_vm:
        cluster: Default
        kernel_path: /var/kernel/centos8/vmlinuz
        initrd_path: /var/kernel/centos8/initrd.img
        kernel_params: noverifyssl ks={{ ks_host }}/?hostname={{ create_host }} BOOTIF={{ (ovirt_nics.ovirt_nics | first).mac.address }}
        kernel_params_persist: false
        name: '{{ create_host }}'
        state: running
