---
- name: Restart postgresql
  service:
    name: postgresql
    state: restarted

- name: Restart rsyslog
  service:
    name: rsyslog
    state: restarted

- name: Run arbitrary SQL commands to configure server
  command: psql -h 127.0.0.1 -f /tmp/configure.sql
  become_user: postgres
