---
nexus3_downloadUrl: https://download.sonatype.com/nexus/3/latest-unix.tar.gz
nexus3_downloadDir: /opt
nexus3_downloadChecksum: sha256:ae8cc7891942d71cf12c11e1a98d70c1310e788ab44aa95c5d1e7671cc0187e2
nexus3_installDir: /opt/nexus
